/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class acodexm_panorama_NativePanorama */

#ifndef _Included_acodexm_panorama_NativePanorama
#define _Included_acodexm_panorama_NativePanorama
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     acodexm_panorama_NativePanorama
 * Method:    processPanorama
 * Signature: ([JJ)V
 */
JNIEXPORT void JNICALL Java_acodexm_panorama_NativePanorama_processPanorama
        (JNIEnv *, jclass, jlongArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
