/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class study_acodexm_NativePanorama */

#ifndef _Included_study_acodexm_NativePanorama
#define _Included_study_acodexm_NativePanorama
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     study_acodexm_NativePanorama
 * Method:    processPanorama
 * Signature: ([JJ)V
 */
JNIEXPORT void JNICALL Java_study_acodexm_NativePanorama_processPanorama
        (JNIEnv *, jclass, jlongArray, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
