/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class study_acodexm_NativePanorama */

#ifndef _Included_study_acodexm_NativePanorama
#define _Included_study_acodexm_NativePanorama
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     study_acodexm_NativePanorama
 * Method:    processPanorama
 * Signature: ([JJ[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_study_acodexm_NativePanorama_processPanorama
  (JNIEnv *, jclass, jlongArray, jlong, jobjectArray);

/*
 * Class:     study_acodexm_NativePanorama
 * Method:    cropPanorama
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_study_acodexm_NativePanorama_cropPanorama
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     study_acodexm_NativePanorama
 * Method:    getProgress
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_study_acodexm_NativePanorama_getProgress
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
